Bring back `CONFIG_HAVE_MEMFD_CREATE` to fix Android build error
Commit 732bf609b670 ("test/io_uring_register: kill old memfd test")
removed the `CONFIG_HAVE_MEMFD_CREATE`, which was previously used to
conditionally provide `memfd_create()` for an old test in
`test/io_uring_register.c`.

Reintroduce `CONFIG_HAVE_MEMFD_CREATE` to resolve Android build error
caused by commit:

  93d3a7a70b4a ("examples/zcrx: udmabuf backed areas")

It added a call to `memfd_create()`, which is unavailable on some
Android toolchains, leading to the following build error:
```
  zcrx.c:111:10: error: call to undeclared function 'memfd_create'; ISO C99 and \
  later do not support implicit function declarations \
  [-Wimplicit-function-declaration]
    111 |         memfd = memfd_create("udmabuf-test", MFD_ALLOW_SEALING);
        |                 ^
```
Then, provide memfd_create() in examples/ if `CONFIG_HAVE_MEMFD_CREATE`
is not set to fix the build error.

v2 -> v3:
  - Don't bother touching the test/ dir.
    Link: https://lore.kernel.org/io-uring/3b28fddb-2171-4f2f-9729-0c0ed14d20cc@kernel.dk

v1 -> v2:
  - Omit the old memfd test because it's not needed anymore.
    Link: https://lore.kernel.org/io-uring/4bc75566-9cb5-42ec-a6b7-16e04062e0c6@kernel.dk

Co-authored-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>
Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>
Signed-off-by: Alviro Iskandar Setiawan <alviro.iskandar@gnuweeb.org>